filebeat.inputs:
  - type: log
    enabled: true
    # Я запущу filebeat в докере и проброшу логи приложения по данному пути
    paths:
      - /usr/share/filebeat/access.log
    # В fields мы можем указать дополнительные поля, а затем в logstash вытаскивать их
    # и делать какую-нибудь дополнительную работу с логами
    fields:
      # Название нашего сервиса
      service: nginx_log

  - type: log
    enabled: true
    paths:
      - /usr/share/filebeat/redis-server.log
    fields:
      service: redis_log

  - type: log
    enabled: true
    paths:
      - /log_gen/log_gen.log

    fields:
      service: log_gen
      organisation: netology

output.logstash:
  hosts: ["logstash:5044"]